// Source/AIDnD_TopDown/Public/Combat/AI/AIDecisionMaker.h
#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "Combat/CombatTypes.h"
#include "AIDecisionMaker.generated.h"

class ACombatCharacter;
class UCombatAction;

// ----------------------------------------------------------------
//  Context structures
// ----------------------------------------------------------------

/** Snapshot of a single target (enemy or ally) for AI decision making */
USTRUCT(BlueprintType)
struct AIDND_TOPDOWN_API FAITargetInfo
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TObjectPtr<ACombatCharacter> Character;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    float HPPercent = 1.f;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    int32 CurrentHP = 0;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    int32 ArmorClass = 10;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    float DistanceFeet = 0.f;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TArray<EConditionType> ActiveConditions;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    bool bIsAlive = true;
};

/** One available action option presented to the AI */
USTRUCT(BlueprintType)
struct AIDND_TOPDOWN_API FAIActionOption
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TSubclassOf<UCombatAction> ActionClass;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    FText ActionName;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    float Range = 5.f;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    EActionType ActionType = EActionType::Action;
};

/** Full battle context passed to AI for decision making */
USTRUCT(BlueprintType)
struct AIDND_TOPDOWN_API FAIBattleContext
{
    GENERATED_BODY()

    // Self
    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TObjectPtr<ACombatCharacter> SelfCharacter;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    FDnDStats SelfStats;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    int32 SelfHP = 0;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    int32 SelfMaxHP = 0;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TArray<EConditionType> SelfConditions;

    // Enemies and allies
    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TArray<FAITargetInfo> Enemies;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TArray<FAITargetInfo> Allies;

    // Available actions
    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TArray<FAIActionOption> AvailableActions;

    // Map info
    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TArray<FVector> ReachableTiles;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    int32 CurrentRound = 1;
};

/** Type of decision the AI has made */
UENUM(BlueprintType)
enum class EAIDecisionType : uint8
{
    Move        UMETA(DisplayName = "Move"),
    Attack      UMETA(DisplayName = "Attack"),
    UseAbility  UMETA(DisplayName = "Use Ability"),
    Dodge       UMETA(DisplayName = "Dodge"),
    Help        UMETA(DisplayName = "Help"),
    Dash        UMETA(DisplayName = "Dash"),
    EndTurn     UMETA(DisplayName = "End Turn")
};

/** Decision returned by the AI */
USTRUCT(BlueprintType)
struct AIDND_TOPDOWN_API FAIDecision
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    EAIDecisionType DecisionType = EAIDecisionType::EndTurn;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TObjectPtr<ACombatCharacter> TargetCharacter;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    FVector TargetLocation = FVector::ZeroVector;

    UPROPERTY(BlueprintReadWrite, Category = "AI")
    TSubclassOf<UCombatAction> ChosenAction;

    /** Reasoning text — ChatGPT writes explanation here, Local AI writes heuristic name */
    UPROPERTY(BlueprintReadWrite, Category = "AI")
    FString Reasoning;

    /** True if this decision was generated by fallback (timeout, error) */
    UPROPERTY(BlueprintReadWrite, Category = "AI")
    bool bIsFallback = false;
};

// ----------------------------------------------------------------
//  Delegate for async decisions
// ----------------------------------------------------------------

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnDecisionReady, FAIDecision, Decision);

// ----------------------------------------------------------------
//  UAIDecisionMaker — abstract base
// ----------------------------------------------------------------

/**
 * Abstract base for AI decision makers.
 * Swap implementations without changing AEnemyAIController.
 *
 * ULocalAIDecisionMaker  — simple heuristics (current)
 * UChatGPTAIDecisionMaker — async GPT API (future)
 */
UCLASS(Abstract, BlueprintType, Blueprintable)
class AIDND_TOPDOWN_API UAIDecisionMaker : public UObject
{
    GENERATED_BODY()

public:

    /** Delegate fired when decision is ready (sync or async) */
    UPROPERTY(BlueprintAssignable, Category = "AI")
    FOnDecisionReady OnDecisionReady;

    /**
     * Request a decision. May be synchronous (Local) or async (ChatGPT).
     * Always fires OnDecisionReady when complete.
     */
    UFUNCTION(BlueprintCallable, BlueprintNativeEvent, Category = "AI")
    void RequestDecision(const FAIBattleContext& Context);

    virtual void RequestDecision_Implementation(
        const FAIBattleContext& Context) PURE_VIRTUAL(
            UAIDecisionMaker::RequestDecision_Implementation, );

    /**
     * Build a battle context from the current game state.
     * Called by AEnemyAIController before RequestDecision.
     */
    UFUNCTION(BlueprintCallable, Category = "AI")
    static FAIBattleContext BuildContext(ACombatCharacter* InSelf,
        const TArray<ACombatCharacter*>& AllCombatants);
};